### ISSUE TITLE
Upgrade http dependency

### ISSUE THREAD

**Issue by brookman** [jamiewest/signalr_core#101]
Thank you for providing this package to the Dart/Flutter community.
Currently signalr_core depends on an older version of http (^0.13.0). This prevents us from upgrading other packages like realm. 
Would it be possible to upgrade it to 1.0.0 or 1.1.0? Thanks in advance.

Problem:

```
Because no versions of signalr_core match >1.1.1 <2.0.0 and signalr_core 1.1.1 depends on http ^0.13.0, signalr_core ^1.1.1 requires http ^0.13.0.
And because realm >=1.3.0 depends on http ^1.0.0, signalr_core ^1.1.1 is incompatible with realm >=1.3.0.
So, because app depends on both realm ^1.3.0 and signalr_core ^1.1.1, version solving failed.
```

**Comment by nukeolay** [comment]
@brookman you can use @RCSandberg version that now in pull requests.
Just add this to your pubspec.yaml:
```
  signalr_core:
    git:
      url: https://github.com/RCSandberg/signalr_core.git
      ref: feature/bump-dart-and-package-versions
```
