### ISSUE TITLE
Pub Get Failed

### ISSUE THREAD

**Issue by ghulamostafa** [jamiewest/signalr_core#45]
Because every version of signalr_core depends on web_socket_channel ^1.1.0 and skipq depends on web_socket_channel ^2.0.0, signalr_core is forbidden.
So, because skipq depends on signalr_core ^1.0.8, version solving failed.

When I compared my pubspec.yaml with the one in repository, I have the same version of Web Socket. But apparently I am still stuck.

**Comment by jamiewest** [comment]
A recent PR checked in null safe code which updated web_socket_channel to 2.0.0. I will be publishing an updated package to pub.dev soon which will hopefully fix this issue.

**Comment by ghulamostafa** [comment]
> A recent PR checked in null safe code which updated web_socket_channel to 2.0.0. I will be publishing an updated package to pub.dev soon which will hopefully fix this issue.

Do we have any update on it?

**Comment by jamiewest** [comment]
Sorry for the delay, I need to run a few more checks but I have not been able to get the time to work on this. Until I publish are you able to reference the package via git? 

```yaml
dependencies:
  signalr_core:
    git:
      url: git@github.com:jamiewest/signalr_core.git
      ref: 7e8eaaf7a7940c60385a076625b75f126a1292d7
```

The ref I referenced is the one that had null safety added. Hopefully this helps, otherwise I will try and get it out soon.
